using System.Globalization;

namespace Migrato.Core;

/// <summary>
/// Jazyk aplikace: uložená volba uživatele, jinak čeština při českých Windows
/// a angličtina jinde. / User's saved choice; otherwise Czech on Czech Windows,
/// English elsewhere.
/// </summary>
public static class Lang
{
    private static readonly string PrefPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "Migrato", "language");

    public static string Current { get; set; } = LoadInitial();

    public static bool IsCz => Current == "cs";

    private static string LoadInitial()
    {
        try
        {
            if (File.Exists(PrefPath))
            {
                string saved = File.ReadAllText(PrefPath).Trim();
                if (saved is "cs" or "en") return saved;
            }
        }
        catch
        {
            // Poškozená/nedostupná volba — použije se jazyk Windows.
        }
        return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "cs" ? "cs" : "en";
    }

    /// <summary>Přepne jazyk a zapamatuje si volbu pro příští spuštění.</summary>
    public static void Save(string lang)
    {
        if (lang is not ("cs" or "en")) return;
        Current = lang;
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(PrefPath)!);
            File.WriteAllText(PrefPath, lang);
        }
        catch
        {
            // Volba platí aspoň do konce běhu aplikace.
        }
    }
}

/// <summary>
/// Katalog textů jádra. Chyby posílané protistraně přes drát se kódují
/// (viz WireError), aby si je každá strana zobrazila ve svém jazyce.
/// </summary>
public static class S
{
    public static string T(string cs, string en) => Lang.IsCz ? cs : en;

    // ---- známé složky / known folders ----
    public static string FolderTitle(string name) => name switch
    {
        "Desktop" => T("Plocha", "Desktop"),
        "Documents" => T("Dokumenty", "Documents"),
        "Downloads" => T("Stažené soubory", "Downloads"),
        "Pictures" => T("Obrázky", "Pictures"),
        "Music" => T("Hudba", "Music"),
        "Videos" => T("Videa", "Videos"),
        "Favorites" => T("Oblíbené položky", "Favorites"),
        _ => name,
    };

    // ---- skenování zdroje / source scanning ----
    public static string Scanning(string what) => T($"Prohledávám: {what}…", $"Scanning: {what}…");
    public static string ScanningApps => T("Zjišťuji nainstalované programy…", "Collecting installed programs…");
    public static string ExportingWifi => T("Exportuji Wi-Fi profily…", "Exporting Wi-Fi profiles…");
    public static string InstalledProgramsTitle => T("Nainstalované programy", "Installed programs");
    public static string InstalledProgramsDesc(int count) => count > 0
        ? T($"Nalezeno {count} programů — na novém PC se automaticky doinstalují přes winget, seznam se uloží na plochu",
            $"Found {count} programs — they will be reinstalled on the new PC via winget; a list is saved to the desktop")
        : T("Na novém PC se programy automaticky doinstalují přes winget",
            "Programs will be reinstalled on the new PC via winget");
    public static string WifiTitle => T("Wi-Fi sítě a hesla", "Wi-Fi networks and passwords");
    public static string WifiDesc(int count) =>
        T($"{count} uložených sítí — nový PC se připojí sám", $"{count} saved networks — the new PC connects automatically");
    public static string ProgramsReportFile =>
        T("Programy ze starého počítače.txt", "Programs from the old computer.txt");
    public static string ProgramsReportHeader(string machine) =>
        T($"Programy nainstalované na počítači {machine}", $"Programs installed on computer {machine}");
    public static string ProgramsReportGenerated(DateTime when) =>
        T($"Vygenerováno aplikací Migrato {when:d. M. yyyy H:mm}", $"Generated by Migrato on {when:yyyy-MM-dd HH:mm}");
    public static string ProgramsReportVersion(string v) => T($"(verze {v})", $"(version {v})");

    // ---- příjem / receiving ----
    public static string WaitingForConnection(string pin) => T($"Čekám na spojení (PIN: {pin})…", $"Waiting for connection (PIN: {pin})…");
    public static string InvalidPinKeepWaiting => T("Neplatný PIN — čekám dál…", "Invalid PIN — still waiting…");
    public static string PairedWith(string machine) => T($"Spárováno s: {machine}", $"Paired with: {machine}");
    public static string ConnectionFailedKeepWaiting(string reason) =>
        T($"Spojení selhalo: {reason} — čekám dál…", $"Connection failed: {reason} — still waiting…");
    public static string IncompatibleKeepWaiting =>
        T("Starý počítač má nekompatibilní verzi aplikace — čekám dál…", "The old computer runs an incompatible app version — still waiting…");
    public static string RunningPostActions => T("Provádím dokončovací akce…", "Running finishing steps…");
    public static string TransferFinished => T("Přenos dokončen.", "Transfer finished.");
    public static string TooManyPinAttempts =>
        T("Příliš mnoho neplatných pokusů o spárování. Spusťte příjem znovu (vygeneruje se nový PIN).",
          "Too many invalid pairing attempts. Start receiving again (a new PIN will be generated).");
    public static string SelfFileSkipped =>
        T("Soubor patří běžící aplikaci Migrato — přeskočen.", "The file belongs to the running Migrato app — skipped.");
    public static string CannotCreateFolder(string reason) =>
        T($"Cílovou složku nelze vytvořit: {reason}", $"Cannot create the target folder: {reason}");
    public static string FileWriteFailed(string reason) => T($"Zápis souboru selhal: {reason}", $"File write failed: {reason}");
    public static string ChecksumMismatch =>
        T("Kontrolní součet nesouhlasí — soubor bude přenesen příště znovu.", "Checksum mismatch — the file will be re-sent next time.");
    public static string MoveToTargetFailed(string reason) =>
        T($"Přesun na cílové místo selhal: {reason}", $"Moving into place failed: {reason}");
    public static string PartFileShrunk =>
        T("Rozpracovaný soubor je kratší, než bylo ohlášeno.", "The partial file is shorter than announced.");
    public static string ConnectionLostMidFile =>
        T("Spojení bylo přerušeno uprostřed souboru.", "The connection dropped in the middle of a file.");

    // ---- navazování / resuming ----
    public static string VerifyingResumed =>
        T("Ověřuji dříve přenesená data (nic se neposílá znovu) — u velkých objemů to může několik minut trvat…",
          "Verifying previously transferred data (nothing is re-sent) — this can take a few minutes for large amounts…");
    public static string TransferringFiles => T("Přenáším soubory…", "Transferring files…");

    // ---- odesílání / sending ----
    public static string Connecting => T("Připojuji se…", "Connecting…");
    public static string PairingWith(string? machine) => T($"Páruji se s {machine}…", $"Pairing with {machine}…");
    public static string SendingManifest(int files) => T($"Odesílám manifest ({files} souborů)…", $"Sending manifest ({files} files)…");
    public static string PeerRunningPostActions =>
        T("Cílový počítač provádí dokončovací akce (instalace programů mohou trvat)…",
          "The target computer is running finishing steps (installing programs may take a while)…");
    public static string VersionMismatchNote(string ours, string theirs) =>
        T($"Pozor: různé verze aplikace (zde {ours}, protějšek {theirs}).",
          $"Note: different app versions (this side {ours}, peer {theirs}).");
    public static string FileShrunk(string path) =>
        T($"Soubor se od naskenování zkrátil: {path}", $"The file shrank after scanning: {path}");
    public static string FileEndedEarly(string path) =>
        T($"Soubor skončil dříve, než měl: {path}", $"The file ended earlier than expected: {path}");
    public static string PairingFailed => T("Párování selhalo.", "Pairing failed.");
    public static string UnknownError => T("neznámá chyba", "unknown error");

    // ---- dokončovací akce / post actions ----
    public static string OnlyOnWindows => T("Tato akce funguje jen na Windows.", "This step works only on Windows.");
    public static string UnknownAction => T("Neznámá akce.", "Unknown action.");
    public static string WingetExportMissing =>
        T("Soubor s exportem programů nedorazil.", "The program export file did not arrive.");
    public static string InstallingPrograms => Modules.Elevation.IsElevated
        ? T("Instaluji programy přes winget — může trvat desítky minut…",
            "Installing programs via winget — this can take a long time…")
        : T("Instaluji programy přes winget — může trvat desítky minut a Windows se bude ptát výzvami UAC (potvrzujte je)…",
            "Installing programs via winget — this can take a long time and Windows will show UAC prompts (please confirm them)…");
    public static string ProgramsInstalled => T("Programy nainstalovány.", "Programs installed.");
    public static string ProgramsPartlyFailed =>
        T("Některé programy se nepodařilo nainstalovat automaticky (podrobnosti v logu winget).",
          "Some programs could not be installed automatically (see the winget log for details).");
    public static string ImportingWifi => T("Importuji Wi-Fi profily…", "Importing Wi-Fi profiles…");
    public static string WifiAdded(int ok) => T($"Přidáno {ok} Wi-Fi sítí.", $"Added {ok} Wi-Fi networks.");
    public static string WifiPartlyFailed(int ok, int failed) =>
        T($"Přidáno {ok} Wi-Fi sítí, {failed} se nepodařilo.", $"Added {ok} Wi-Fi networks, {failed} failed.");
    public static string NoInstallNeeded => T("Bez instalace.", "No installation needed.");
    public static string AppAlreadyInstalled => T("Aplikace už je nainstalovaná.", "The app is already installed.");
    public static string InstallingApp(string id) => T($"Instaluji {id}…", $"Installing {id}…");
    public static string AppInstalled => T("Aplikace nainstalována.", "App installed.");
    public static string AppInstallFailed(string id) =>
        T($"Aplikaci {id} se nepodařilo nainstalovat — nainstalujte ji ručně, data už jsou na místě.",
          $"Could not install {id} — install it manually, its data is already in place.");

    // ---- nástroje / tools ----
    public static string ToolStartFailed(string tool) =>
        T($"Nástroj {tool} se nepodařilo spustit.", $"Could not start the {tool} tool.");
    public static string ToolUnavailable(string tool, string reason) =>
        T($"Nástroj {tool} není dostupný: {reason}", $"The {tool} tool is not available: {reason}");
    public static string ToolTimedOut(string tool, int seconds) =>
        T($"Nástroj {tool} nestihl doběhnout v limitu {seconds} s.", $"The {tool} tool did not finish within {seconds} s.");

    // ---- vzhled / appearance ----
    public static string LookTitle => T("Vzhled — tapeta a písma", "Appearance — wallpaper and fonts");
    public static string LookDesc(bool wallpaper, int fonts)
    {
        string wp = wallpaper ? T("tapeta plochy", "desktop wallpaper") : "";
        string f = fonts > 0 ? T($"{fonts} uživatelských písem", $"{fonts} user fonts") : "";
        string joined = (wp, f) switch
        {
            ("", var only) => only,
            (var only, "") => only,
            _ => $"{wp} + {f}",
        };
        return T($"Přenese se {joined}", $"Transfers {joined}");
    }
    public static string WallpaperSet => T("Tapeta nastavena.", "Wallpaper set.");
    public static string FontsRegistered(int n) =>
        T($"Zaregistrováno {n} písem.", $"Registered {n} fonts.");
    public static string LookNothingApplied =>
        T("Žádná položka vzhledu nedorazila.", "No appearance items arrived.");

    // ---- navazování a opakování / resume & retry ----
    public static string RetryingFailed(int n) =>
        T($"Zkouším znovu {n} neúspěšných souborů…", $"Retrying {n} failed files…");
    public static string Paused =>
        T("Pozastaveno — spojení zůstává otevřené.", "Paused — the connection stays open.");

    // ---- vlastní složky / custom folders ----
    public static string TransferredFoldersDir => T("Přenesené složky", "Transferred folders");
    public static string CustomFolderDesc(string path) =>
        T($"{path} — na novém PC přistane na ploše ve složce „Přenesené složky“",
          $"{path} — will land on the new PC's desktop in the “Transferred folders” folder");

    // ---- místo na disku / disk space ----
    public static string NotEnoughSpace(long needed, long free) =>
        T($"Na cílovém počítači není dost místa na disku (potřeba {Format.Bytes(needed)}, volných {Format.Bytes(free)}). Uvolněte místo nebo zmenšete výběr.",
          $"Not enough disk space on the target computer (need {Format.Bytes(needed)}, {Format.Bytes(free)} free). Free up space or reduce the selection.");

    // ---- protokol o přenosu / transfer report ----
    public static string ReportTitle => T("Protokol o přenosu — Migrato", "Transfer report — Migrato");
    public static string ReportDirectionSent => T("Role: odesílatel (starý počítač)", "Role: sender (old computer)");
    public static string ReportDirectionReceived => T("Role: příjemce (nový počítač)", "Role: receiver (new computer)");
    public static string ReportSummary(int ok, int failed, long bytes) =>
        T($"Souborů v pořádku: {ok}, selhalo: {failed}, přeneseno: {Format.Bytes(bytes)}",
          $"Files OK: {ok}, failed: {failed}, transferred: {Format.Bytes(bytes)}");
    public static string ReportPostActions => T("Dokončovací akce:", "Finishing steps:");
    public static string ReportErrors => T("Chyby:", "Errors:");
    public static string ReportNoErrors => T("Žádné chyby.", "No errors.");

    // ---- chyby přes drát / wire errors ----
    // Kódy se lokalizují až na straně, která je zobrazuje.
    public const string WireInvalidPin = "#invalidPin";
    public const string WireIncompatiblePrefix = "#incompatible|";

    public static string DecodeWireError(string error)
    {
        if (error == WireInvalidPin)
            return T("Neplatný PIN.", "Invalid PIN.");
        if (error.StartsWith(WireIncompatiblePrefix, StringComparison.Ordinal))
        {
            string theirs = error[WireIncompatiblePrefix.Length..];
            return T($"Nekompatibilní verze aplikace (protějšek {theirs}, zde {AppVersion.Current}). Aktualizujte Migrato na obou počítačích.",
                     $"Incompatible app versions (peer {theirs}, this side {AppVersion.Current}). Update Migrato on both computers.");
        }
        return error;
    }
}
